### ISSUE TITLE
Error while running rq-dashboard via command line

### ISSUE THREAD

**Issue by pyjads** [eoranged/rq-dashboard#475]
**Describe the bug**

**To Reproduce**
I started redis server using following docker-compose.yml
```yml
version: '3'
services:
  redis:
    image: docker.io/redis:7.2.3
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - .:/etc/redis
    ports:
        - "6379:6379"
```

redis.conf looks like below

`requirepass 123456`

I am trying to use rq-dashboard to connect to the redis using below commands locally

```
pip install rq-dashboard


rq-dashboard --password 123456 -u redis://localhost:6379 --debug -v --bind 0.0.0.0
```

I get below error/logs:

```
* Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9181
 * Running on http://10.236.44.184:9181
Press CTRL+C to quit
 * Restarting with stat
RQ Dashboard version 0.6.7
 * Debugger is active!
 * Debugger PIN: 584-485-599



127.0.0.1 - - [20/Nov/2023 23:34:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Nov/2023 23:34:00] "GET /favicon.ico HTTP/1.1" 304 -
```
Why do I get Connection Error in the browser. The logs are also not much of help. Could anyone look into this.
Thank you in advance.
**Additional context**
 - OS: MacOS 14
 - Python Version 3.11
